import './globals.css'
import { Oxanium } from 'next/font/google';
import LayoutWrapper from "@/components/layoutWrapper";
import { SpeedInsights } from '@vercel/speed-insights/next';

const oxanium = Oxanium({ 
  subsets: ['latin'],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${oxanium.variable} overscroll-none`}>
        <LayoutWrapper>
          {children}
          <SpeedInsights />
        </LayoutWrapper>
      </body>
    </html>
  )
}
